name: Deploy repositorio-sgq

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account: 'github-action-894104225@repositorio-sgq.iam.gserviceaccount.com'
          project_id: 'repositorio-sgq'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          site: repositorio-sgq.firebaseapp.com
          project: 1:733023742365:web:1af0a8579b3f1a66f0a774
          auth: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
  
  name: Build
        run: npm run build

  name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
